# Generated by Django 3.2.5 on 2021-07-31 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('TagId', models.AutoField(primary_key=True, serialize=False)),
                ('Tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textsnippet',
            fields=[
                ('SnippetId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Textsnippet', to='textsnippets.tags', verbose_name='Tags')),
            ],
        ),
    ]
